################### Dnsbeat Configuration Example #########################

############################# Dnsbeat ######################################

dnsbeat:
  zones:
    - fqdn: "example.com."
      nameservers:
        - hostname: dns:53
      timeouts:
        dial: 2s
        read: 5s
      period: 5m
processors:
- add_cloud_metadata: ~
- add_docker_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
